# system-manager implementation of the shared FS-Cache schema.
#
# cachefilesd is an Arch-owned package and unit. This module owns the desired
# configuration and lifecycle, while the consuming host maps
# nixshare.archPackages to its package reconciler. That keeps nixshare free of
# a hard dependency on any particular Arch package manager module.
{ config, lib, ... }:

let
  fsc = config.nixshare.fscache;
  w = fsc.watermarks;
  cachefilesdConf = ''
    # Generated by nixshare. Do not edit.
    dir ${fsc.cacheDir}
    tag ${fsc.tag}
    brun ${toString w.brun}%
    bcull ${toString w.bcull}%
    bstop ${toString w.bstop}%
    frun ${toString w.frun}%
    fcull ${toString w.fcull}%
    fstop ${toString w.fstop}%
    ${fsc.extraConfig}
  '';
in
{
  imports = [ ../providers/fscache.nix ];

  config = lib.mkIf (config.nixshare.enable && fsc.enable) {
    # Pacman owns this file, so system-manager must take it over explicitly.
    # Future upgrades then produce a .pacnew instead of silently overwriting
    # the Git-declared configuration.
    environment.etc."cachefilesd.conf" = {
      replaceExisting = true;
      text = cachefilesdConf;
    };

    # cachefilesd normally loads this itself, but making the kernel capability
    # explicit means the service never depends on package-unit implementation
    # details and keeps working after an upstream unit refactor.
    environment.etc."modules-load.d/nixshare-fscache.conf".text = ''
      # Managed by nixshare.
      cachefiles
    '';

    # Reconciles the foreign distro unit after system-manager has written the
    # new configuration. Consumers that use a package reconciler should order
    # this after it; the unit intentionally has no nixarch dependency.
    systemd.services.nixshare-cachefilesd-reconcile = {
      description = "nixshare: enable and apply the cachefilesd service";
      wantedBy = [ "multi-user.target" ];
      restartTriggers = [ config.environment.etc."cachefilesd.conf".source ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "/usr/bin/systemctl enable --now cachefilesd.service";
        ExecStartPost = "/usr/bin/systemctl restart cachefilesd.service";
      };
    };
  };
}
